# Generated by Django 2.2.11 on 2020-05-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='课程号')),
                ('course_name', models.CharField(max_length=20, unique=True, verbose_name='课程名')),
                ('course_status', models.CharField(max_length=20, verbose_name='课程状态')),
                ('course_college', models.CharField(choices=[('1', '信息科学与技术学院'), ('2', '材料科学与工程学院'), ('3', '机电工程学院'), ('4', '化学工程学院'), ('5', '经济管理学院'), ('6', '化学学院'), ('7', '数理学院'), ('8', '文法学院'), ('9', '生命科学与技术学院'), ('10', '继续教育学院'), ('11', '马克思主义学院'), ('12', '国际教育学院'), ('13', '侯德榜工程师学院'), ('14', '巴黎居里工程师学院')], default='信息科学与技术', max_length=20, verbose_name='开课学院')),
                ('course_pre_id', models.CharField(max_length=20, verbose_name='先修课程号')),
                ('course_pre_name', models.CharField(max_length=20, verbose_name='先修课程名')),
                ('course_introduction', models.CharField(max_length=1000, verbose_name='课程介绍')),
            ],
            options={
                'verbose_name': '课程信息表',
                'verbose_name_plural': '课程信息表',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='通知号')),
                ('notice_send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送日期')),
                ('notice_content', models.CharField(max_length=1000, verbose_name='通知内容')),
                ('notice_title', models.CharField(max_length=255, verbose_name='通知标题')),
            ],
            options={
                'verbose_name': '公告表',
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('student_age', models.PositiveSmallIntegerField(null=True, verbose_name='年龄')),
                ('student_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20, null=True, verbose_name='性别')),
                ('student_nation', models.CharField(choices=[('1', '汉族'), ('2', '满族'), ('3', '回族'), ('4', '藏族'), ('5', '维吾尔族'), ('6', '苗族'), ('7', '彝族'), ('8', '壮族'), ('9', '布依族'), ('10', '侗族'), ('11', '瑶族'), ('12', '白族'), ('14', '土家族'), ('15', '哈尼族'), ('16', '哈萨克族'), ('17', '傣族'), ('18', '傈僳族'), ('19', '佤族'), ('20', '畲族'), ('21', '高山族'), ('22', '拉祜族'), ('23', '水族'), ('24', '东乡族'), ('25', '纳西族'), ('26', '景颇族'), ('27', '柯尔克孜族'), ('28', '土族'), ('29', '达斡尔族'), ('30', '仫佬族'), ('31', '羌族'), ('32', '布朗族'), ('33', '撒拉族'), ('34', '毛南族'), ('35', '仡佬族'), ('36', '锡伯族'), ('37', '阿昌族'), ('38', '普米族'), ('39', '朝鲜族'), ('40', '塔吉克族'), ('41', '怒族'), ('42', '乌孜别克族'), ('43', '俄罗斯族'), ('44', '鄂温克族'), ('45', '德昂族'), ('46', '保安族'), ('47', '裕固族'), ('48', '京族'), ('49', '塔塔尔族'), ('50', '独龙族'), ('51', '鄂伦春族'), ('52', '赫哲族'), ('53', '门巴族'), ('54', '珞巴族'), ('55', '基诺族'), ('56', '黎族')], default='汉族', max_length=20, null=True, verbose_name='民族')),
                ('student_political_status', models.CharField(choices=[('1', '中共党员'), ('2', '共青团员'), ('3', '群众')], default='群众', max_length=20, null=True, verbose_name='政治面貌')),
                ('student_come_year', models.DateField(null=True, verbose_name='入学日期')),
                ('student_college', models.CharField(choices=[('1', '信息科学与技术学院'), ('2', '材料科学与工程学院'), ('3', '机电工程学院'), ('4', '化学工程学院'), ('5', '经济管理学院'), ('6', '化学学院'), ('7', '数理学院'), ('8', '文法学院'), ('9', '生命科学与技术学院'), ('10', '继续教育学院'), ('11', '马克思主义学院'), ('12', '国际教育学院'), ('13', '侯德榜工程师学院'), ('14', '巴黎居里工程师学院')], default='信息科学与技术学院', max_length=20, null=True, verbose_name='学院')),
                ('student_major', models.CharField(max_length=20, null=True, verbose_name='专业')),
                ('student_class', models.CharField(max_length=20, null=True, verbose_name='班级')),
                ('student_province', models.CharField(max_length=20, null=True, verbose_name='省份')),
                ('student_city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('student_birthday', models.DateField(null=True, verbose_name='出生日期')),
                ('student_qq', models.CharField(max_length=20, null=True, verbose_name='QQ号码')),
                ('student_wechat', models.CharField(max_length=20, null=True, verbose_name='微信号码')),
                ('student_high_school', models.CharField(max_length=20, null=True, verbose_name='毕业高中')),
                ('student_foreign_language', models.CharField(choices=[('1', '英语'), ('2', '法语'), ('3', '日语'), ('4', '俄语')], default='英语', max_length=20, null=True, verbose_name='外语')),
                ('student_status', models.CharField(choices=[('1', '在读'), ('2', '毕业')], default='在读', max_length=20, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('teacher_name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('teacher_age', models.PositiveSmallIntegerField(null=True, verbose_name='年龄')),
                ('teacher_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20, null=True, verbose_name='性别')),
                ('teacher_nation', models.CharField(choices=[('1', '汉族'), ('2', '满族'), ('3', '回族'), ('4', '藏族'), ('5', '维吾尔族'), ('6', '苗族'), ('7', '彝族'), ('8', '壮族'), ('9', '布依族'), ('10', '侗族'), ('11', '瑶族'), ('12', '白族'), ('14', '土家族'), ('15', '哈尼族'), ('16', '哈萨克族'), ('17', '傣族'), ('18', '傈僳族'), ('19', '佤族'), ('20', '畲族'), ('21', '高山族'), ('22', '拉祜族'), ('23', '水族'), ('24', '东乡族'), ('25', '纳西族'), ('26', '景颇族'), ('27', '柯尔克孜族'), ('28', '土族'), ('29', '达斡尔族'), ('30', '仫佬族'), ('31', '羌族'), ('32', '布朗族'), ('33', '撒拉族'), ('34', '毛南族'), ('35', '仡佬族'), ('36', '锡伯族'), ('37', '阿昌族'), ('38', '普米族'), ('39', '朝鲜族'), ('40', '塔吉克族'), ('41', '怒族'), ('42', '乌孜别克族'), ('43', '俄罗斯族'), ('44', '鄂温克族'), ('45', '德昂族'), ('46', '保安族'), ('47', '裕固族'), ('48', '京族'), ('49', '塔塔尔族'), ('50', '独龙族'), ('51', '鄂伦春族'), ('52', '赫哲族'), ('53', '门巴族'), ('54', '珞巴族'), ('55', '基诺族'), ('56', '黎族')], default='汉族', max_length=20, null=True, verbose_name='民族')),
                ('teacher_political_status', models.CharField(choices=[('1', '中共党员'), ('2', '共青团员'), ('3', '群众')], default='群众', max_length=20, null=True, verbose_name='政治面貌')),
                ('teacher_department', models.CharField(max_length=20, null=True, verbose_name='部门')),
                ('teacher_academic_title', models.CharField(choices=[('1', '助教'), ('2', '讲师'), ('3', '副教授'), ('4', '教授')], default='教授', max_length=20, null=True, verbose_name='职称')),
                ('teacher_degree', models.CharField(choices=[('1', '学士'), ('2', '硕士'), ('3', '博士')], default='学士', max_length=20, null=True, verbose_name='学位')),
                ('teacher_come_year', models.DateTimeField(null=True, verbose_name='入职日期')),
                ('teacher_province', models.CharField(max_length=20, null=True, verbose_name='省份')),
                ('teacher_city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('teacher_birthday', models.DateTimeField(null=True, verbose_name='出生日期')),
                ('teacher_qq', models.CharField(max_length=20, null=True, verbose_name='QQ号码')),
                ('teacher_wechat', models.CharField(max_length=20, null=True, verbose_name='微信号码')),
                ('teacher_graduate_school', models.CharField(max_length=20, null=True, verbose_name='毕业院校')),
            ],
            options={
                'verbose_name': '教师信息表',
                'verbose_name_plural': '教师信息表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('identity', models.CharField(choices=[('student', '学生'), ('teacher', '教师')], default='学生', max_length=20, verbose_name='身份')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '用户登录表',
                'verbose_name_plural': '用户登录表',
                'unique_together': {('account', 'identity')},
            },
        ),
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_year', models.CharField(max_length=20, verbose_name='开始年份')),
                ('end_year', models.CharField(max_length=20, verbose_name='结束年份')),
                ('number', models.IntegerField(verbose_name='学期号')),
            ],
            options={
                'verbose_name': '学期表',
                'verbose_name_plural': '学期表',
                'unique_together': {('begin_year', 'end_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='消息号')),
                ('message_content', models.CharField(max_length=1000, verbose_name='消息内容')),
                ('message_send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送日期')),
                ('message_status', models.CharField(max_length=20, verbose_name='消息状态')),
                ('message_title', models.CharField(max_length=255, verbose_name='消息标题')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '消息表',
                'verbose_name_plural': '消息表',
            },
        ),
        migrations.CreateModel(
            name='SelectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('term', models.CharField(max_length=20, verbose_name='学期')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('volume', models.IntegerField(verbose_name='容量')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course', verbose_name='课程号')),
            ],
            options={
                'verbose_name': '选课清单表',
                'verbose_name_plural': '选课清单表',
                'unique_together': {('major', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, verbose_name='学期')),
                ('student_grade', models.CharField(max_length=20, verbose_name='成绩')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course', verbose_name='课程号')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '选课表',
                'verbose_name_plural': '选课表',
                'unique_together': {('student_id', 'term', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, verbose_name='学期')),
                ('week', models.CharField(max_length=20, verbose_name='周次')),
                ('session', models.CharField(max_length=20, verbose_name='节次')),
                ('location', models.CharField(max_length=20, verbose_name='地点')),
                ('weekday', models.CharField(max_length=20, verbose_name='上课日期')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course', verbose_name='课程号')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Teacher', verbose_name='工号')),
            ],
            options={
                'verbose_name': '课程安排表',
                'verbose_name_plural': '课程安排表',
                'unique_together': {('course_id', 'term', 'teacher_id')},
            },
        ),
    ]
