# Generated by Django 2.2.11 on 2020-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200506_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.CharField(max_length=20, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_come_year',
            field=models.CharField(max_length=20, null=True, verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_birthday',
            field=models.CharField(max_length=20, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_come_year',
            field=models.CharField(max_length=20, null=True, verbose_name='入职日期'),
        ),
    ]
