# Generated by Django 2.2.11 on 2020-04-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200425_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_city',
            field=models.CharField(max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=20, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_college',
            field=models.CharField(choices=[('1', '信息科学与技术学院'), ('2', '材料科学与工程学院'), ('3', '机电工程学院'), ('4', '化学工程学院'), ('5', '经济管理学院'), ('6', '化学学院'), ('7', '数理学院'), ('8', '文法学院'), ('9', '生命科学与技术学院'), ('10', '继续教育学院'), ('11', '马克思主义学院'), ('12', '国际教育学院'), ('13', '侯德榜工程师学院'), ('14', '巴黎居里工程师学院')], default='信息科学与技术学院', max_length=20, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_come_year',
            field=models.DateField(null=True, verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_foreign_language',
            field=models.CharField(choices=[('1', '英语'), ('2', '法语'), ('3', '日语'), ('4', '俄语')], default='英语', max_length=20, null=True, verbose_name='外语'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_high_school',
            field=models.CharField(max_length=20, null=True, verbose_name='毕业高中'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_major',
            field=models.CharField(max_length=20, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_nation',
            field=models.CharField(choices=[('1', '汉族'), ('2', '满族'), ('3', '回族'), ('4', '藏族'), ('5', '维吾尔族'), ('6', '苗族'), ('7', '彝族'), ('8', '壮族'), ('9', '布依族'), ('10', '侗族'), ('11', '瑶族'), ('12', '白族'), ('14', '土家族'), ('15', '哈尼族'), ('16', '哈萨克族'), ('17', '傣族'), ('18', '傈僳族'), ('19', '佤族'), ('20', '畲族'), ('21', '高山族'), ('22', '拉祜族'), ('23', '水族'), ('24', '东乡族'), ('25', '纳西族'), ('26', '景颇族'), ('27', '柯尔克孜族'), ('28', '土族'), ('29', '达斡尔族'), ('30', '仫佬族'), ('31', '羌族'), ('32', '布朗族'), ('33', '撒拉族'), ('34', '毛南族'), ('35', '仡佬族'), ('36', '锡伯族'), ('37', '阿昌族'), ('38', '普米族'), ('39', '朝鲜族'), ('40', '塔吉克族'), ('41', '怒族'), ('42', '乌孜别克族'), ('43', '俄罗斯族'), ('44', '鄂温克族'), ('45', '德昂族'), ('46', '保安族'), ('47', '裕固族'), ('48', '京族'), ('49', '塔塔尔族'), ('50', '独龙族'), ('51', '鄂伦春族'), ('52', '赫哲族'), ('53', '门巴族'), ('54', '珞巴族'), ('55', '基诺族'), ('56', '黎族')], default='汉族', max_length=20, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_political_status',
            field=models.CharField(choices=[('1', '中共党员'), ('2', '共青团员'), ('3', '群众')], default='群众', max_length=20, null=True, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_province',
            field=models.CharField(max_length=20, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_qq',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('1', '在读'), ('2', '毕业')], default='在读', max_length=20, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_wechat',
            field=models.CharField(max_length=20, null=True, verbose_name='微信号码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_academic_title',
            field=models.CharField(choices=[('1', '助教'), ('2', '讲师'), ('3', '副教授'), ('4', '教授')], default='教授', max_length=20, null=True, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_birthday',
            field=models.DateTimeField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_city',
            field=models.CharField(max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_degree',
            field=models.CharField(choices=[('1', '学士'), ('2', '硕士'), ('3', '博士')], default='学士', max_length=20, null=True, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_department',
            field=models.CharField(max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_graduate_school',
            field=models.CharField(max_length=20, null=True, verbose_name='毕业院校'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_nation',
            field=models.CharField(choices=[('1', '汉族'), ('2', '满族'), ('3', '回族'), ('4', '藏族'), ('5', '维吾尔族'), ('6', '苗族'), ('7', '彝族'), ('8', '壮族'), ('9', '布依族'), ('10', '侗族'), ('11', '瑶族'), ('12', '白族'), ('14', '土家族'), ('15', '哈尼族'), ('16', '哈萨克族'), ('17', '傣族'), ('18', '傈僳族'), ('19', '佤族'), ('20', '畲族'), ('21', '高山族'), ('22', '拉祜族'), ('23', '水族'), ('24', '东乡族'), ('25', '纳西族'), ('26', '景颇族'), ('27', '柯尔克孜族'), ('28', '土族'), ('29', '达斡尔族'), ('30', '仫佬族'), ('31', '羌族'), ('32', '布朗族'), ('33', '撒拉族'), ('34', '毛南族'), ('35', '仡佬族'), ('36', '锡伯族'), ('37', '阿昌族'), ('38', '普米族'), ('39', '朝鲜族'), ('40', '塔吉克族'), ('41', '怒族'), ('42', '乌孜别克族'), ('43', '俄罗斯族'), ('44', '鄂温克族'), ('45', '德昂族'), ('46', '保安族'), ('47', '裕固族'), ('48', '京族'), ('49', '塔塔尔族'), ('50', '独龙族'), ('51', '鄂伦春族'), ('52', '赫哲族'), ('53', '门巴族'), ('54', '珞巴族'), ('55', '基诺族'), ('56', '黎族')], default='汉族', max_length=20, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_political_status',
            field=models.CharField(choices=[('1', '中共党员'), ('2', '共青团员'), ('3', '群众')], default='群众', max_length=20, null=True, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_province',
            field=models.CharField(max_length=20, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_qq',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ号码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_wechat',
            field=models.CharField(max_length=20, null=True, verbose_name='微信号码'),
        ),
    ]
