# Generated by Django 2.2.11 on 2020-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200506_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_birthday',
            field=models.CharField(max_length=255, null=True, verbose_name='出生日期'),
        ),
    ]
